### ISSUE TITLE
Using useGLTF from react-three-drei

### ISSUE THREAD

**Issue by Mjorldir** [pmndrs/leva#391] opened 2022-10-13 09:12 UTC
When I use a list of GLTF files to show its 3D image, at the begining they all show, but when I try to select the ones I selected before, the image will not show again.
Looks like once the image was showed it doesn't re-renders and there is no browser memory to show it back.
Do you know how to fix this? I tried attaching a useEffect when the list changes but doesn't work.

`import { useEffect } from 'react'
import { Canvas } from '@react-three/fiber'
import { useGLTF, OrbitControls} from '@react-three/drei'
import {useControls} from 'leva'
import Papir1 from '../resources/BP_LD.gltf'
import Papir2 from '../resources/CC_LD.gltf'
import Papir3 from '../resources/MC_LD.gltf'

export default function Papir3D() {

    const papirs = {      
        "1137 - Berenguer i Petronella" : Papir1,
        "1412 - Compromis de Casp": Papir2,
        "1605-1608 Mapa Cathalonia": Papir3
    }    

    const {papir} = useControls({transient: false, papir: { options: Object.keys(papirs) } })

    useEffect(() => {

    }, [papir])

    function Model({ url, ...props }) {
        const { scene } = useGLTF(url)
        return <primitive object={scene} {...props} />
    }

    return(
        <>
        <Canvas camera={{ position: [2, 1, 2], fov: 25 }}>
            <hemisphereLight color="white" groundColor="blue" intensity={0.75} />
            <spotLight position={[50, 50, 10]} angle={0.15} penumbra={1} />
            <Model position={[0, 0, 0]} url={papirs[papir]} />         
            <OrbitControls />
        </Canvas>
        </>

    )
}`

**Comment by kkbandaru** [comment] 2022-10-18 10:51
i am also having same question how to update the controls input when props changes

**Comment by dbismut** [comment] 2022-10-18 11:42
Please make a sandbox.

**Comment by kkbandaru** [comment] 2022-10-18 13:17
https://codesandbox.io/s/levasandbox-5bv9lc?file=/src/App.js

here is very basic example, when ever when some  parent component send props updates, in child component which is rendered should get updated value in leva component

**Comment by dbismut** [comment] 2022-10-19 19:39
@kkbandaru I'm not sure how the sandbox is relevant to the above, but no, Leva doesn't recompute its schema on props change. You need to add a dependency to the schema if you want to, and even though it won't change the props value. This is by design.

Here's a working version of your sandbox anyway. Not sure it has the best render flow (clearly not to be honest since you will have a double render, but anyway)...

https://codesandbox.io/s/levasandbox-forked-dt7hp6?file=/src/App.js

**Comment by dbismut** [comment] 2022-10-22 13:16
Closing until there's a proper sandbox showing the problem!

**Closed by dbismut** 2022-10-22 13:16 UTC

**Comment by Mjorldir** [comment] 2022-10-25 06:15
This is the sandbox of a working project with simple images, it works perfect:
[https://codesandbox.io/s/pairing-threejs-to-ui-wlz1o0?file=/src/App.js:558-619](url) 

The problem is when I use larger files.
I can't upload more than 50Mb to sandbox, so just 2 of 3 files:
[https://codesandbox.io/s/shy-framework-e4hubp?file=/src/App.js](url)

When you change the file, it remembers the last one displayed.

**Comment by Mjorldir** [comment] 2022-10-26 06:26
Added a sandbox to this issue:

https://github.com/pmndrs/leva/issues/391#issuecomment-1284486608
